SET NAMES utf8mb4;

-- Sexe de l'adhérent : 'F', 'H' ou '' (non renseigné). Utilisé pour le petit bonhomme SAM de la messagerie
-- (une fille pour les filles) ; renseigné par le bureau dans la fiche adhérent.
ALTER TABLE members ADD COLUMN sexe CHAR(1) NOT NULL DEFAULT '' AFTER statut;

-- Adhérents de démonstration uniquement (demo.*@demo-samparis12.test) : sexe déduit du prénom fictif.
-- Les vrais comptes ne sont jamais touchés ; les prénoms absents des deux listes restent non renseignés.
UPDATE members SET sexe = 'F'
WHERE email LIKE 'demo.%@demo-samparis12.test' AND sexe = ''
  AND prenom IN ('Marie','Sophie','Nathalie','Isabelle','Catherine','Julie','Sylvie','Claire','Anne','Camille','Céline','Christine','Françoise','Monique','Martine','Valérie','Véronique','Sandrine','Stéphanie','Laurence','Florence','Hélène','Brigitte','Dominique','Patricia','Corinne','Annie','Nicole','Jacqueline','Christelle','Aurélie','Émilie','Emilie','Amélie','Laetitia','Élodie','Elodie','Delphine','Virginie','Karine','Sabrina','Audrey','Caroline','Charlotte','Laure','Pauline','Marine','Sarah','Léa','Lea','Manon','Chloé','Chloe','Emma','Inès','Ines','Jeanne','Louise','Alice','Julia','Margaux','Mathilde','Océane','Clara','Lucie','Agnès','Agnes','Béatrice','Béatrix','Cécile','Colette','Danielle','Denise','Édith','Edith','Éliane','Eliane','Evelyne','Éveline','Fabienne','Geneviève','Genevieve','Ghislaine','Gisèle','Josiane','Joëlle','Joelle','Lydie','Magali','Marianne','Maryse','Michèle','Michele','Mireille','Muriel','Nadine','Odile','Pascale','Sonia','Sylviane','Thérèse','Therese','Yvette','Yvonne','Zoé','Zoe','Fatima','Samira','Nadia','Leïla','Leila','Yasmine','Aïcha','Aicha','Amina','Rachida','Malika','Maria','Ana','Rosa','Elena','Giulia','Laura','Paula','Carla','Sofia','Isabel','Eva','Lina','Nina','Nora','Ève','Eve','Anaïs','Anais','Estelle','Gaëlle','Gaelle','Hélène','Jessica','Justine','Lisa','Mélanie','Melanie','Morgane','Noémie','Noemie','Priscilla','Romane','Solène','Solene','Typhaine','Vanessa','Violette');

UPDATE members SET sexe = 'H'
WHERE email LIKE 'demo.%@demo-samparis12.test' AND sexe = ''
  AND prenom IN ('Jean','Pierre','Philippe','Michel','Thomas','Nicolas','Laurent','David','Alain','André','Andre','Antoine','Arnaud','Benoît','Benoit','Bernard','Bruno','Christian','Christophe','Claude','Daniel','Denis','Didier','Dominique','Éric','Eric','Étienne','Etienne','Fabien','Fabrice','François','Francois','Frédéric','Frederic','Gérard','Gerard','Gilles','Guillaume','Henri','Hervé','Herve','Jacques','Jérôme','Jerome','Joël','Joel','Julien','Laurent','Loïc','Loic','Luc','Marc','Mathieu','Maxime','Olivier','Patrice','Patrick','Paul','Pascal','Rémi','Remi','René','Rene','Richard','Robert','Roland','Sébastien','Sebastien','Serge','Stéphane','Stephane','Sylvain','Thierry','Vincent','Xavier','Yann','Yves','Alexandre','Adrien','Alex','Arthur','Baptiste','Clément','Clement','Damien','Édouard','Edouard','Émile','Emile','Florent','Gabriel','Hugo','Jules','Kévin','Kevin','Léo','Leo','Louis','Lucas','Mathis','Nathan','Noah','Raphaël','Raphael','Romain','Samuel','Simon','Théo','Theo','Tristan','Valentin','Victor','Antonio','Carlos','Jose','José','Manuel','Miguel','Pedro','Luis','Mohamed','Karim','Rachid','Ahmed','Youssef','Omar','Mehdi','Hassan','Ali','Farid','Samir','Marco','Giovanni','Luca','Paolo','Joao','João');
